config/routes.rb
Rails.application.routes.draw do
  	
  	root "home#index"

  	resources :services, only:[:index, :new, :create, :destroy, :edit, :update]

  	get "services/open" => "services#open"
  	get "services/:id/finish" => "services#finish", as: :finish_service
  	get "services/search" => "services#search"

  	get "services/:id" => "services#show"
  	
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/service.rb
class Service < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController

	def index
		@services = Service.all
	end

	def new
		@service = Service.new
	end

	def create
		values = params.require(:service).permit!
		@service = Service.create values

		if @service.save
			redirect_to services_open_path, notice: 'Ordem de Serviço Cadastrada com Sucesso!'
		else
			render :new
		end
	end

	def destroy
		id = params[:id]
		Service.destroy id
		redirect_to services_open_path, notice: 'Ordem de Serviço Excluída!'
	end

	def edit
		@service = Service.find(params[:id])
	end

	def update
		@service = Service.find(params[:id])
		values = params.require(:service).permit!
		@service.update values

		if @service.save
			redirect_to @service, notice: 'Ordem de Serviço Alterada com Sucesso!'
		elsif
			render :edit
		end
	end

	def open
		@services = Service.where "status like ?", "Aberta"
	end

	def finish
		@service = Service.find(params[:id])

		if @service.status == 'Aberta'
			@service.update(status: 'Concluída')
			redirect_to @service, notice: 'Ordem de Serviço Concluída com Sucesso!'
		else
			redirect_to @service, notice: 'Ordem de serviço ja esta finalizada!'
		end
	end

	def search
		@client = params[:client]
		@services = Service.where "client like ?", "%#{@client}%"
	end

	def show
		@service = Service.find(params[:id])
		respond_to do |format|
			format.html
			format.pdf { render template: "services/print", pdf: 'print'}
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ernandescelulares</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div id="barra_de_logo">
      <p class="logo"><%= image_tag "ernandes.jpg", :width => "250px", :height => "100px"%></p>
    </div>

    <input type="checkbox" id="bt_menu">
    <label for="bt_menu">&#9776;</label>

    <nav class="menus">
      <ul>
        <li><%= link_to 'Home', root_path %></li>
        <li><a href="">Ordens de Serviço</a>
          <ul>
            <li><%= link_to "Nova O.S", new_service_path %></li>
            <li><%= link_to "Ordens de Serviço", services_path %></li>
            <li><%= link_to "Abertas", services_open_path, method: :get %></li>
          </ul>
        </li>
        <li><a href="">Despesas</a>
          <ul>
            <li><a href="">Nova Despesa</a></li>
            <li><a href="">Todas Despesas</a></li>
          </ul>
        </li>
      </ul>

    </nav>

    <div class="primary-container">
      <%= yield %>
    </div>
    
  </body>
</html>

app/views/services/_form_service.html.erb
<div class="form-center">
	<%= form_for @service do |f| %>

		<div class="form-group">
			<%= f.label :cliente %>
			<%= f.text_field :client, class: "form-control" %>
		</div>

		<div class="form-group">
			<%= f.label :telefone %>
			<%= f.text_field :fone, class: "form-control" %>
		</div>

		<div class="form-group">
			<%= f.label :endereco %>
			<%= f.text_field :address, class: "form-control" %>
		</div>

		<div class="form-group">
			<%= f.label :descricao %>
			<%= f.text_area :description, class: "form-control" %>
		</div>

		<div class="form-group">
			<%= f.label :valor %>
			<%= f.text_field :value, class: "form-control" %>
		</div>

		<div class="form-group">
			<%= f.label :previsao %>
			<%= f.text_field :delivery, class: "form-control" %>
		</div>

		<div class="form-group">
			<%= f.label :status %><br>
			<%= f.select :status, ['Aberta', 'Concluída'], class: "form-control" %>
		</div>

		<div class="form-group">
			<%= f.submit :salvar, class: "btn btn-success" %>
		</div>
	<% end %>
</div>

app/views/services/_services.html.erb
<table class="table table-bordered">
	<thead>
		<tr>
			<th>Ordem</th>
			<th>Data</th>
			<th>Cliente</th>
			<th>Telefone</th>
			<th>Valor</th>
			<th>Status</th>
		</tr>
	</thead>
	<tbody>
		<% @services.each do |service| %>
		<tr>
			<td><%= service.id %></td>
			<td><%= service.created_at.strftime("%d/%m/%Y") %></td>
			<td><%= service.client %></td>
			<td><%= service.fone %></td>
			<td><%= service.value %></td>
			<td><%= service.status %></td>
			<td class="button"><%= link_to "Exibir", service, class: "btn btn-primary" %></td>	
		</tr>
		<% end %>
	</tbody>
</table>

app/views/services/edit.html.erb
<div class="label">
	<h2>O.S Nº <%= @service.id %></h2>
</div>

<div class="options">
	<%= link_to 'Voltar', @service, class: "btn btn-default" %>
</div>

<%= render 'form_service' %>

app/views/services/index.html.erb
<% if flash[:notice] %>
	<div class="alert alert-info" role="alert">
	  	<%= flash[:notice] %>
	</div>
<% end %>

<div class="label">
	<h2>Ordens de Serviço</h2>
</div>

<%= form_tag services_search_path, method: :get, class: "navbar-form navbar-right" do %>
	<div class="form-group">
		<%= text_field_tag :client, @client, class: "form-control" %>
		<%= button_to 'Buscar', nil, class: "btn btn-success" %>
	</div>
<% end %>

<%= render "services" %>

app/views/services/new.html.erb
<div class="label">
	<h2>Nova O.S</h2>
</div>


<%= render 'form_service' %>

app/views/services/open.html.erb
<% if flash[:notice] %>
	<div class="alert alert-info" role="alert">
	  	<%= flash[:notice] %>
	</div>
<% end %>

<div class="label">
	<h2>O.S Abertas</h2>
</div>

<%= render "services" %>

app/views/services/print.pdf.erb
<!DOCTYPE html>
<html>
	<head>
		<%= wicked_pdf_stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
		<title>Ordem de serviço</title>
		<meta charset="utf-8">
	</head>
	<body style="background: white;">

		<div class="container-primary">

			<p style="margin-left: 6em; margin-bottom: 3em;"><%= wicked_pdf_image_tag 'ernandes.jpg', :width => "250px", :height => "100px"%><p>
		
			<h2 align="center">Ordem de Serviço Nº <%= @service.id%></h2>

			<div class="container-secundary">
				<div class="line">
					<label>Data:</label>
					<span><%= @service.created_at.strftime("%d/%m/%Y") %></span>
				</div>

				<div class="line">
					<label>Cliente:</label>
					<span><%= @service.client %></span>
				</div>

				<div class="line">
					<label>Telefone:</label>
					<span><%= @service.fone %></span>
				</div>

				<div class="line">
					<label>Endereço:</label>
					<span><%= @service.address %></span>
				</div>

				<div class="line">
					<label>Descrição:</label><br>
					<p><%= @service.description %></p>
				</div>

				<div class="line">
					<label>Valor:</label>
					<span>R<%= number_to_currency @service.value %></span>
				</div>

				<div class="line">
					<label>Cliente:</label>
					<span><%= @service.client %></span>
				</div>
			</div>
		</div>
	</body>
</html>

app/views/services/search.html.erb
<% if flash[:notice] %>
	<div class="alert alert-info" role="alert">
	  	<%= flash[:notice] %>
	</div>
<% end %>

<div class="label">
	<h2>O.S Abertas</h2>
</div>

<%= form_tag services_search_path, method: :get, class: "navbar-form navbar-right" do %>
	<div class="form-group">
		<%= link_to 'Voltar', services_open_path, class: "btn btn-default" %> 
		<%= text_field_tag :client, @client, class: "form-control" %>
		<%= button_to 'Buscar', nil, class: "btn btn-success" %>
	</div>
<% end %>

<%= render "services" %>

app/views/services/show.html.erb
<% if flash[:notice] %>
	<div class="alert alert-info" role="alert">
		<%= flash[:notice]%>
	</div>
<% end %>

<div class="label">
	<h2>Ordem de Serviço Nº <%= @service.id%></h2>
</div>

<div style="float: left; margin-left: 5em;">
	<%= link_to(image_tag("imprimir.png", :width => "50px", :height => '50px'), "#{@service.id}.pdf") %>
</div>

<div class="options">
	<%= link_to 'Voltar', services_open_path, class: "btn btn-default" %>
	<%= link_to "Editar", edit_service_path(@service), class: "btn btn-warning" %>
	<%= link_to 'Excluir', @service, method: :delete, class: "btn btn-danger", data:{confirm: "Deseja excluir a O.S Nº #{@service.id}"} %>
	<%= link_to "Finalizar", finish_service_path(@service), data:{confirm: "Deseja Finalizar a ordem de serviço nº #{@service.id}"}, class: "btn btn-success" %>
</div>

<div class="form-center">
	<%= form_for @service do |f| %>

		<div class="form-group">
			<%= f.label :ordem %>
			<%= f.text_field :id, class: "form-control", :disabled=>true %>
		</div>

		<div class="form-group">
			<%= f.label :cliente %>
			<%= f.text_field :client, class: "form-control", :disabled=>true %>
		</div>

		<div class="form-group">
			<%= f.label :telefone %>
			<%= f.text_field :fone, class: "form-control", :disabled=>true %>
		</div>

		<div class="form-group">
			<%= f.label :endereco %>
			<%= f.text_field :address, class: "form-control", :disabled=>true %>
		</div>

		<div class="form-group">
			<%= f.label :descricao %>
			<%= f.text_area :description, class: "form-control", :disabled=>true %>
		</div>

		<div class="form-group">
			<%= f.label :valor %>
			<%= f.text_field :value, class: "form-control", :disabled=>true %>
		</div>

		<div class="form-group">
			<%= f.label :previsao %>
			<%= f.text_field :delivery, class: "form-control", :disabled=>true %>
		</div>

		<div class="form-group">
			<%= f.label :status %><br>
			<%= f.text_field :status, class: "form-control", :disabled=>true %>
		</div>

	<% end %>
</div>